-- MySQL Script generated by MySQL Workbench
-- Thu Feb 24 20:00:59 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema latiendita
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema latiendita
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `latiendita` DEFAULT CHARACTER SET utf8 ;
USE `latiendita` ;

-- -----------------------------------------------------
-- Table `latiendita`.`administradores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `latiendita`.`administradores` (
  `idadministradores` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidopaterno` VARCHAR(45) NOT NULL,
  `apellidomaterno` VARCHAR(45) NULL DEFAULT NULL,
  `fotoperfil` VARCHAR(100) NULL DEFAULT NULL,
  `fechanacimiento` DATE NOT NULL,
  `edad` INT NULL,
  `direccion` VARCHAR(250) NOT NULL,
  `codigopostal` CHAR(5) NOT NULL,
  `telcelular` VARCHAR(20) NOT NULL,
  `telcasa` VARCHAR(20) NULL,
  `tipousuario` CHAR(4) NOT NULL COMMENT 'SA = Superadministrador\nA = Administrador',
  `email` VARCHAR(150) NOT NULL,
  `passw` VARCHAR(270) NOT NULL,
  `nombreusuario` VARCHAR(45) NOT NULL,
  `fecharegistro` DATETIME NOT NULL,
  `fechaactualizacion` DATETIME NULL,
  `estado` CHAR(1) NOT NULL COMMENT 'E = Eliminado\nA = Activo',
  `idusuarioregistro` INT NOT NULL,
  `idusuarioelimino` INT NULL,
  PRIMARY KEY (`idadministradores`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `latiendita`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `latiendita`.`productos` (
  `idproductos` INT NOT NULL AUTO_INCREMENT,
  `idadministradoresfk` INT NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `descripcionespecifica` VARCHAR(150) NOT NULL,
  `descripciongeneral` VARCHAR(1000) NOT NULL,
  `estadoproducto` VARCHAR(25) NOT NULL,
  `precio` DOUBLE NOT NULL,
  `descuento` INT NULL DEFAULT 0 COMMENT '0% a 100%',
  `stock` INT NULL DEFAULT 0,
  `likes` INT NULL DEFAULT 0,
  `fecharegistro` DATETIME NOT NULL,
  `fechaactualizacion` DATETIME NULL,
  `estado` CHAR(1) NOT NULL,
  `idusuarioregistro` INT NOT NULL,
  `idusuarioelimino` INT NULL,
  PRIMARY KEY (`idproductos`),
  INDEX `fk_productos_administradores1_idx` (`idadministradoresfk` ASC),
  CONSTRAINT `fk_productos_administradores1`
    FOREIGN KEY (`idadministradoresfk`)
    REFERENCES `latiendita`.`administradores` (`idadministradores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `latiendita`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `latiendita`.`categorias` (
  `idcategorias` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `descripcion` VARCHAR(150) NOT NULL,
  `fecharegistro` DATETIME NOT NULL,
  `fechaactualizacion` DATETIME NULL,
  `estado` CHAR(1) NOT NULL,
  `idusuarioregistro` INT NOT NULL,
  `idusuarioelimino` INT NULL,
  PRIMARY KEY (`idcategorias`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `latiendita`.`productos_categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `latiendita`.`productos_categorias` (
  `idproductos_categorias` INT NOT NULL AUTO_INCREMENT,
  `idproductosfk` INT NOT NULL,
  `idcategoriasfk` INT NOT NULL,
  `fecharegistro` DATETIME NOT NULL,
  `fechaactualizacion` DATETIME NULL,
  `estado` CHAR(1) NOT NULL,
  `idusuarioregistro` INT NOT NULL,
  `idusuarioelimino` INT NULL,
  INDEX `fk_productos_categorias_productos1_idx` (`idproductosfk` ASC),
  PRIMARY KEY (`idproductos_categorias`),
  INDEX `fk_productos_categorias_categorias1_idx` (`idcategoriasfk` ASC),
  CONSTRAINT `fk_productos_categorias_productos1`
    FOREIGN KEY (`idproductosfk`)
    REFERENCES `latiendita`.`productos` (`idproductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_productos_categorias_categorias1`
    FOREIGN KEY (`idcategoriasfk`)
    REFERENCES `latiendita`.`categorias` (`idcategorias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `latiendita`.`imagenesproductos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `latiendita`.`imagenesproductos` (
  `idimagenesproductos` INT NOT NULL AUTO_INCREMENT,
  `idproductos_categorias` INT NOT NULL,
  `nombreimagen` VARCHAR(150) NOT NULL,
  `tipoimagen` VARCHAR(10) NOT NULL,
  `fecharegistro` DATETIME NOT NULL,
  `fechaactualizacion` DATETIME NULL,
  `estado` CHAR(1) NOT NULL,
  `idusuarioregistro` INT NOT NULL,
  `idusuarioelimino` INT NULL,
  PRIMARY KEY (`idimagenesproductos`),
  INDEX `fk_imagenesproductos_productos_categorias1_idx` (`idproductos_categorias` ASC),
  CONSTRAINT `fk_imagenesproductos_productos_categorias1`
    FOREIGN KEY (`idproductos_categorias`)
    REFERENCES `latiendita`.`productos_categorias` (`idproductos_categorias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `latiendita`.`pivotetable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `latiendita`.`pivotetable` (
  `idpivotetable` INT NOT NULL AUTO_INCREMENT,
  `fecharegistro` DATETIME NOT NULL,
  `fechaactualizacion` DATETIME NULL,
  `estado` CHAR(1) NOT NULL,
  `idusuarioregistro` INT NOT NULL,
  `idusuarioelimino` INT NULL,
  PRIMARY KEY (`idpivotetable`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `latiendita`.`permisos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `latiendita`.`permisos` (
  `idpermisos` INT NOT NULL AUTO_INCREMENT,
  `permiso` CHAR(1) NOT NULL COMMENT 'E = Eliminar\nQ = Consultar\nA = Actualizar\nC = Crear',
  `fecharegistro` DATETIME NOT NULL,
  `fechaactualizacion` DATETIME NULL DEFAULT NULL,
  `estado` CHAR(1) NOT NULL COMMENT 'E = Eliminado\nA = Ac',
  `idusuarioregistro` INT NOT NULL,
  `idusuarioelimino` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idpermisos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `latiendita`.`administradores_permisos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `latiendita`.`administradores_permisos` (
  `idadministradoresfk` INT NOT NULL,
  `idpermisosfk` INT NOT NULL,
  INDEX `fk_administradores_has_permisos_permisos1_idx` (`idpermisosfk` ASC),
  INDEX `fk_administradores_has_permisos_administradores1_idx` (`idadministradoresfk` ASC),
  CONSTRAINT `fk_administradores_has_permisos_administradores1`
    FOREIGN KEY (`idadministradoresfk`)
    REFERENCES `latiendita`.`administradores` (`idadministradores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_administradores_has_permisos_permisos1`
    FOREIGN KEY (`idpermisosfk`)
    REFERENCES `latiendita`.`permisos` (`idpermisos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
